apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-text-processor-deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-text-processor  
  template:
    metadata:
      labels:
        app: my-text-processor  
    spec:
      containers:
      - name: my-text-processor  
        image: aayushkeshari/my_text_processor
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
